### ISSUE TITLE
Native is nil? new update?!

### ISSUE THREAD

**Issue by LielXD** [dsheedes/cd_easytime#16]
![image](https://user-images.githubusercontent.com/60383662/164943083-369c9851-db83-486d-8bd9-0db674751362.png)
it says this native isnt working ↓
SetArtificialLightsStateAffectsVehicles(toggle)

**Comment by polar1s7** [comment]
What artifact version is this?

**Comment by polar1s7** [comment]
Try gamebuild 2545.

**Comment by RampBST** [comment]
We have just pushed a new update (v1.3.4) to support new and old game builds
