### ISSUE TITLE
You dont have the Permission....

### ISSUE THREAD

**Issue by MisterNIO** [dsheedes/cd_easytime#22]
Hey,

after hours of locking at the screen i finally write this here cause i hate it too when ppl first ask and then look...but i dont know what i did wrong.

So, i have rewritten the config file for QB and i dont get any errors in my Console or Server Log, but i still get the massage that i dont have the permission to use this command.

I first tried it with "admin" and then with "god" but i still cant open the Menu.
I dont have any other weather script on my Server but it wont work.

I have read the Guide over and over but i cant help myself.

So if you have a bit of spare time, maybe you know what is wrong^^

This is my config file:
Config.FrameworkTriggers = { --You can change the esx/qbcore events (IF NEEDED).
    main = 'QBCore:GetObject',   --ESX = 'esx:getSharedObject'   QBCORE = 'QBCore:GetObject'
    load = 'QBCore:Client:OnPlayerLoaded',      --ESX = 'esx:playerLoaded'      QBCORE = 'QBCore:Client:OnPlayerLoaded'
    job = 'QBCore:Client:OnJobUpdate',             --ESX = 'esx:setJob'            QBCORE = 'QBCore:Client:OnJobUpdate'
    resource_name = 'qb-core'   --ESX = 'es_extended'           QBCORE = 'qb-core'
}

Config.NotificationType = { --[ 'esx' / 'qbcore' / 'mythic_old' / 'mythic_new' / 'chat' / 'other' ] Choose your notification script.
    server = 'qbcore',
    client = 'qbcore' 
}

Config.Command = {
    OpenUI = 'easytime', --The command for staff to open the UI.

    Perms = { --You decide which permission groups can use the staff command ^.
        ['qbcore'] = {'god', 'admin'}
    }
}

Thx to you guys^^

**Comment by Zzeyy** [comment]
Permissions work fine for me. (ESX)
