### ISSUE TITLE
Dynamic Weather setting not saving through server restart

### ISSUE THREAD

**Issue by Mynameisnotlenny** [dsheedes/cd_easytime#25]
Hey, resource has been working great so far, I have noticed that if you disable dynamic weather to keep it snowing as an example the setting isn't saved through a restart, the server will restart and have the previously saved weather however the dynamic weather setting ends up resetting and the weather will end up changing.

**Comment by JanBlk** [comment]
the previous commit was wrong, this one is correct 
![image](https://user-images.githubusercontent.com/70229762/205523834-d47edec0-ed1e-4276-bc1a-faea53c562bd.png)
