### ISSUE TITLE
no rain seen

### ISSUE THREAD

**Issue by Ashember** [dsheedes/cd_easytime#30]
No Rain.  all other weather works, however, you can not see the raindrops or any puddles on the ground.

https://user-images.githubusercontent.com/23489428/236870547-4b085167-a7ef-4c21-9cbc-15aa3eecaf61.mp4

no errors, and no one is seeing the rain at all. we see the fog, clouds, lighting, no water

**Comment by WtrpXcal** [comment]
Having the same issue, if I set weather to Rain or Thunderstorm I have the same issue as above. If stop the resource the rain will start to fall. no errors same as above.
