### ISSUE TITLE
Weather Persistant, not changed with command nor config

### ISSUE THREAD

**Issue by LordDrilldo** [dsheedes/cd_easytime#5]
Using unmodified version of script, both on active servers and now testing the plugin pretty-much alone. Have never been able to limit weather. Persistant fog, snow, smog, etc. time works fine. Weather, no update.

**Comment by LordDrilldo** [comment]
No errors no console output etc

**Comment by dsheedes** [comment]
What do you mean by "limit weather"?

**Comment by RampBST** [comment]
Closed due to no response in 2 month
