### ISSUE TITLE
weather and time not sync properly

### ISSUE THREAD

**Issue by sparcoxalpha** [dsheedes/cd_easytime#6]
weather and time not sync properly ,
if we changed time to night and one player exited from server while he reconnect again may be time ll be morning for that player,
many time tried
any fix

but the time transition is very smooth ,i loved it

and add one more feature if can ,like while changing time please try to give some wait and a smooth transition ,no players should not know that time changed, now in this script if we change time its changing very quickly.

**Comment by RampBST** [comment]
Do you use a multicharacter script?

**Comment by sparcoxalpha** [comment]
Nop

**Comment by RampBST** [comment]
What version of the script do you use?

And is there any more info you can provide us with to help you? What your explaining is not a common issue

**Comment by RampBST** [comment]
@sparcoxalpha

**Comment by sparcoxalpha** [comment]
Weather and time not sync between players properly,if admin change time who ever in server all of then can change time as same,but if a new player enter city for that player time ll be different

**Comment by RampBST** [comment]
this has been fixed in the latest versions
