### ISSUE TITLE
Not working with ESX

### ISSUE THREAD

**Issue by blaqqendwhyt** [dsheedes/cd_easytime#9]
Hellow there, first of all nice script !

I have an issues with your script and ESX.

First on startup the permissions check fail

```
[  script:cd_easytime] SCRIPT ERROR: @cd_easytime/server/server.lua:205: attempt to index a nil value (global 'ESX')
[  script:cd_easytime] > PermissionsCheck (@cd_easytime/server/server.lua:205)
[  script:cd_easytime] > ref (@cd_easytime/server/server.lua:39)
```

Next after a restart IG you can see those errors (screen down there)

![image](https://user-images.githubusercontent.com/57453491/143675168-a1c9f193-744a-46b3-b4c1-5ae422eea946.png)

And finaly the command "easytime" look like to work cause it pop up my mouse but the visual does not appear.

Thanks. ^^

**Comment by dsheedes** [comment]
Looks like easytime is loading before ESX can get all the data. 
You can try putting a wait before the permissions check.

For the error on the screenshot it looks like the files inside the `js` folder have been modified somehow, either corrupt download or you have some kind of anticheat that modifies the files.
